ISSUE #435 Change for gtest compilation error in the bouncer test project:
Severity Code Description Project File Line Suppression State
Error C2247 'mongo::BSONObj::begin' not accessible because 'repo::core::model::RepoBSON' uses 'private' to inherit from 'mongo::BSONObj' 3drepobouncerTest C:\DevProjects\3drepobouncer\submodules\googletest\googletest\include\gtest\gtest-printers.h 313